### ISSUE TITLE
MainScheduleResponse

### ISSUE THREAD

**Issue by Soyeonu** [indongzz/daegu_dot_app#25]
1. Main Schedule Register는 가능합니다. return 은 그대로 Main Schedule Id 바꿔주셨으면 합니덩.. MapMainActivity로 넘어갈 때 MainScheduleId를 Intent로 넘겨서 SubSchedule을 탐색합니다!

2. Select MainSchedule에서 status값은 제대로 오는데 MainSchedule담은 List는 null로 반환됩니다. 확인부탁드립니다.,.,.,

**Comment by HGYEONG** [comment]
1. user마다 mainschedule을 여러 개 가질 수 있기 때문에 status 값으로 mainschedule ID 값을 줄 수는 없습니다. 대신 ArrayList에서 각 mainschedule 객체에 mainschedul id 값이 존재하지 해당 값을 사용해주세요.

**Comment by HGYEONG** [comment]
2. 리턴 받는 객체를 선언할 때 변수명과 변수형이 정확하게 일치해야합니다! (객체명은 일치하지 않아도 됨!)

**Comment by HGYEONG** [comment]
1. 질문 이해를 잘 못 했습니다. registerRX함수 호출 시 리턴값 변경을 메인스케줄 id 값으로 처리했습니다.
