### ISSUE TITLE
더보기 UI

### ISSUE THREAD

**Issue by HGYEONG** [indongzz/daegu_dot_app#4]
기존의 더보기 목록 구성: 내 정보 확인, 찜, 알림 기능

알림 기능을 제외하고 '내가 쓴 글'로 변경

내가 쓴 글이 추천 글이 있고 댓글이 있는데...
구성이 변경되다 보니 UI도 변경이 되어야할 것 같아서 질문 올립니다!

추천 글과 댓글을 fragment로 볼 수 있도록 구현할 것인지
아니면 리스트뷰로 목록을 구성한 후 각각의 내용을 볼 것인지

**Comment by Soyeonu** [comment]
내가 쓴 추천글, 댓글을 리스트뷰로 목록 구성 한 후에 작성된 글 UI를 띄우는 것이 좋아보입니다😄

**Comment by HGYEONG** [comment]
네~
