### ISSUE TITLE
더 보기 UI 구현

### ISSUE THREAD

**Issue by HGYEONG** [indongzz/daegu_dot_app#5]
더 보기 UI 큰 틀에 대한 구현은 완료했습니다! (git branch: feature-more)
UI부분에서 추가적으로 수정해야 하는 부분들 입니다!

1. 비밀번호 및 별명 변경 다이어로그 디자인 수정 필요
2.  내가 쓴 글 및 내가 쓴 댓글에 대한 리스트 디자인 수정 필요
3. 찜 에 대한 리스트 디자인 수정 필요
*현재 리스트의 기본 디자인은 더보기의 첫 화면(layout_more_list)로 통일했습니다.*
4. 툴바 뒤로가기 기능 필요

**Comment by Soyeonu** [comment]
더보기 UI 구현 완료 👌
