### ISSUE TITLE
로그인 에러 발생

### ISSUE THREAD

**Issue by HGYEONG** [indongzz/daegu_dot_app#6]
구글 및 카카오 로그인 클릭 시 연동화면으로는 넘어가는데 그 후가 되지 않습니다.
에러 확인 부탁드립니다!

**Comment by Soyeonu** [comment]
저는 다른 기기로 해도 잘 넘어가는데 어떻게 안되는지 알려주세용..
그냥 아무 반응도 없나요??

**Comment by HGYEONG** [comment]
카카오는 수정 후 일정으로 화면이 넘어가는데 구글은 안 넘어갑니다...

**Comment by Soyeonu** [comment]
해결 완료 ~
