### ISSUE TITLE
에러 발생

### ISSUE THREAD

**Issue by HGYEONG** [indongzz/daegu_dot_app#9]
아까 충돌 때 변수명 잘못 옮기셔서 에러 발생한 것 같습니다.
확인 부탁드립니다~
![캡처](https://user-images.githubusercontent.com/35682252/105363455-64df8f80-5c3f-11eb-8696-cb6d8dff8d4f.JPG)

**Comment by Soyeonu** [comment]
변수명 에러는 수정 완료했습니다.
Branch 합치면서 달라진 부분도 차차 수정하겠습니다 🙂
